### ISSUE TITLE
openFile: resource exhausted (Too many open files)

### ISSUE THREAD

**Issue by 3noch** [agentm/project-m36#145] opened 2017-09-18 03:46 UTC
When running a quick benchmark I hit the error `openFile: resource exhausted (Too many open files)`. The benchmark simply inserts a new record 100000 times in a tight loop. Each loop is a *new transaction*. I wanted to see how quickly the database grows.

How are files being written now? This error seems to indicate some sort of lazy file IO.

**Comment by 3noch** [comment] 2017-09-18 04:39
Actually, even stopping and restarting the process I still get this error. Perhaps these are actually being leaked somehow?

**Comment by 3noch** [comment] 2017-09-18 04:40
Even after *rebooting* I still get this error. That leads me to believe that after 31(ish) transactions, Project:M36 is immediately running out of file handles while reading the database.

**Comment by 3noch** [comment] 2017-09-18 04:41
Sometimes the error happens with `openBinaryFile` instead. It's not the same file every time.

**Comment by agentm** [comment] 2017-09-18 13:18
There's probably a leak. Can you share the benchmark source?

**Comment by 3noch** [comment] 2017-09-18 13:23
It'll take me a bit to pull out all the junk surrounding my benchmark...I slapped it together in a minute in an existing project. However, I'll bet just running one of the provided examples with a tight loop would hit the issue.

**Comment by agentm** [comment] 2017-09-18 13:37
I would like to verify that the cause of the leak isn't due to the benchmark.

**Comment by agentm** [comment] 2017-09-19 03:19
I was able to reproduce this using the new "handles" benchmark utility.
Fixed in 717dacaf877eaa3ebb6d81eb22e86c6316ea3e0a.

**Closed by agentm** 2017-09-19 03:19 UTC

**Comment by 3noch** [comment] 2017-09-19 03:24
Wow. Fantastic. You're amazing. Thank you.
